### ISSUE TITLE
Vue3.0支持么?

### ISSUE THREAD

**Issue by kemaosen** [Goldziher/vuex-hooks#3]
我看了写法,按readme的写法 不适用Vue3.0但是我有很想使用use方法
Vue3中使用setup就不在想用options api了 导致我无法使用vuex map 辅助函数,

**Comment by Goldziher** [comment]
Sorry m8, I can't read this 😃, English?

**Comment by kemaosen** [comment]
I'm sorry,My English bad,  but you need a translation software.
